In [1]:
import numpy as np
import pandas as pd

In [2]:
aman = pd.read_csv('aman.csv')

In [3]:
aman

   Unnamed: 0.2  Unnamed: 0.1  Unnamed: 0  Train No  Speed     City
0             0             0           0     14006     50    Bihar
1             1             1           1     56009     80    Patna
2             2             2           2     54009     89   shimla
3             3             3           3     14007     70  kondali

In [4]:
aman['Speed'] [0] = 50

C:\Users\AMAN\AppData\Local\Temp\ipykernel_20976\3427302775.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  aman['Speed'] [0] = 50
C:\Users\AMAN\AppData\Local\Temp\ipykernel_20976\3427302775.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  aman['Speed'] [0] = 50

In [5]:
aman

   Unnamed: 0.2  Unnamed: 0.1  Unnamed: 0  Train No  Speed     City
0             0             0           0     14006     50    Bihar
1             1             1           1     56009     80    Patna
2             2             2           2     54009     89   shimla
3             3             3           3     14007     70  kondali

In [6]:
aman.to_csv('aman.csv')

In [7]:
aman.index = ['First', 'Second', 'Third', 'fourth']

In [8]:
aman

        Unnamed: 0.2  Unnamed: 0.1  Unnamed: 0  Train No  Speed     City
First              0             0           0     14006     50    Bihar
Second             1             1           1     56009     80    Patna
Third              2             2           2     54009     89   shimla
fourth             3             3           3     14007     70  kondali

In [9]:
ser = pd.Series(np.random.rand(34))

In [10]:
type(ser)

pandas.core.series.Series

In [11]:
newdf = pd.DataFrame(np.random.rand(334, 5), index=np.arange(334))

In [12]:
type(newdf)

pandas.core.frame.DataFrame

In [13]:
newdf.describe()

                0           1           2           3           4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean     0.497346    0.485130    0.500233    0.507174    0.512415
std      0.300576    0.289175    0.294248    0.280040    0.290761
min      0.001110    0.000006    0.002299    0.009677    0.003021
25%      0.239445    0.234085    0.243775    0.257888    0.280172
50%      0.487913    0.469750    0.500828    0.494434    0.525021
75%      0.780029    0.722728    0.751691    0.764467    0.759772
max      0.999612    0.998176    0.998501    0.991441    0.996877

In [14]:
newdf[0][0] = "Aman"

C:\Users\AMAN\AppData\Local\Temp\ipykernel_20976\706979197.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf[0][0] = "Aman"
C:\Users\AMAN\AppData\Local\Temp\ipykernel_20976\706979197.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Aman' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  newdf[0][0] = "Aman"

In [15]:
newdf.head()

          0         1         2         3         4
0      Aman  0.638371  0.134022  0.875965  0.699404
1  0.901914  0.726308  0.519687  0.284857  0.183391
2  0.223494  0.182554  0.770933  0.185542  0.012492
3  0.979911  0.841163  0.218306  0.752694  0.551187
4  0.365442  0.088754  0.765917  0.594303  0.766193

In [16]:
newdf.dtypes

0     object
1    float64
2    float64
3    float64
4    float64
dtype: object

In [17]:
newdf.to_numpy()

array([['Aman', 0.6383710215533639, 0.1340219591049907,
        0.8759649146685066, 0.6994042927659142],
       [0.901914063104344, 0.7263084531689391, 0.5196874484681312,
        0.2848574673771739, 0.1833906102931091],
       [0.22349422598509883, 0.18255380198349502, 0.7709325866132658,
        0.18554238256718147, 0.012491519632715442],
       ...,
       [0.9271824468416777, 0.3480228304471682, 0.011711797718239048,
        0.09778402269620923, 0.8054292720542522],
       [0.7783576261686085, 0.30254689793130296, 0.6519542143814748,
        0.49658619120903036, 0.7588528606155903],
       [0.012003600831520855, 0.2275488468535537, 0.9178751168772875,
        0.7770216474465531, 0.8988971959023628]], dtype=object)

In [18]:
newdf[0][0] = 0.8

In [19]:
newdf.T

,0,1,2,3,4,5,6,7,8,9,...,324,325,326,327,328,329,330,331,332,333
0,0.8,0.901914,0.223494,0.979911,0.365442,0.642391,0.864492,0.027247,0.329399,0.524891,...,0.897624,0.938488,0.873618,0.758018,0.275306,0.046155,0.470582,0.927182,0.778358,0.012004
1,0.638371,0.726308,0.182554,0.841163,0.088754,0.759678,0.309568,0.478198,0.554462,0.726228,...,0.101593,0.32692,0.03885,0.633012,0.167257,0.390358,0.08746,0.348023,0.302547,0.227549
2,0.134022,0.519687,0.770933,0.218306,0.765917,0.893152,0.323088,0.250858,0.575144,0.992843,...,0.525195,0.9308,0.186786,0.282319,0.875127,0.752033,0.405831,0.011712,0.651954,0.917875
3,0.875965,0.284857,0.185542,0.752694,0.594303,0.257861,0.35589,0.475094,0.283276,0.297961,...,0.825439,0.945126,0.587457,0.187033,0.318059,0.968696,0.128702,0.097784,0.496586,0.777022
4,0.699404,0.183391,0.012492,0.551187,0.766193,0.512496,0.878985,0.773475,0.730368,0.553734,...,0.294836,0.80608,0.175917,0.942956,0.654662,0.698729,0.702938,0.805429,0.758853,0.898897

In [20]:
newdf.sort_index(axis=0, ascending=False)

            0         1         2         3         4
333  0.012004  0.227549  0.917875  0.777022  0.898897
332  0.778358  0.302547  0.651954  0.496586  0.758853
331  0.927182  0.348023  0.011712  0.097784  0.805429
330  0.470582  0.087460  0.405831  0.128702  0.702938
329  0.046155  0.390358  0.752033  0.968696  0.698729
..        ...       ...       ...       ...       ...
4    0.365442  0.088754  0.765917  0.594303  0.766193
3    0.979911  0.841163  0.218306  0.752694  0.551187
2    0.223494  0.182554  0.770933  0.185542  0.012492
1    0.901914  0.726308  0.519687  0.284857  0.183391
0         0.8  0.638371  0.134022  0.875965  0.699404

[334 rows x 5 columns]

In [21]:
newdf2 = newdf

In [22]:
newdf2[0][0] = 56

In [23]:
newdf.head()

          0         1         2         3         4
0        56  0.638371  0.134022  0.875965  0.699404
1  0.901914  0.726308  0.519687  0.284857  0.183391
2  0.223494  0.182554  0.770933  0.185542  0.012492
3  0.979911  0.841163  0.218306  0.752694  0.551187
4  0.365442  0.088754  0.765917  0.594303  0.766193

In [24]:
newdf2 = newdf.copy()

In [25]:
newdf2[0][0] = 789

C:\Users\AMAN\AppData\Local\Temp\ipykernel_20976\3602959829.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf2[0][0] = 789
C:\Users\AMAN\AppData\Local\Temp\ipykernel_20976\3602959829.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdf2[0][0] = 789

In [26]:
newdf.head()

          0         1         2         3         4
0        56  0.638371  0.134022  0.875965  0.699404
1  0.901914  0.726308  0.519687  0.284857  0.183391
2  0.223494  0.182554  0.770933  0.185542  0.012492
3  0.979911  0.841163  0.218306  0.752694  0.551187
4  0.365442  0.088754  0.765917  0.594303  0.766193

In [27]:
newdf.loc[0, 0] = 654

In [28]:
newdf.head(2)

          0         1         2         3         4
0       654  0.638371  0.134022  0.875965  0.699404
1  0.901914  0.726308  0.519687  0.284857  0.183391

In [29]:
newdf.columns = list('ABCDE')

In [30]:
newdf.loc[0, 0] = 654

In [31]:
newdf.head(2)

          A         B         C         D         E      0
0       654  0.638371  0.134022  0.875965  0.699404  654.0
1  0.901914  0.726308  0.519687  0.284857  0.183391    NaN

In [32]:
newdf.drop(0, axis =1)

            A         B         C         D         E
0         654  0.638371  0.134022  0.875965  0.699404
1    0.901914  0.726308  0.519687  0.284857  0.183391
2    0.223494  0.182554  0.770933  0.185542  0.012492
3    0.979911  0.841163  0.218306  0.752694  0.551187
4    0.365442  0.088754  0.765917  0.594303  0.766193
..        ...       ...       ...       ...       ...
329  0.046155  0.390358  0.752033  0.968696  0.698729
330  0.470582  0.087460  0.405831  0.128702  0.702938
331  0.927182  0.348023  0.011712  0.097784  0.805429
332  0.778358  0.302547  0.651954  0.496586  0.758853
333  0.012004  0.227549  0.917875  0.777022  0.898897

[334 rows x 5 columns]

In [33]:
newdf.loc[0, 'A'] = 6545

In [34]:
newdf.head(2)

          A         B         C         D         E      0
0      6545  0.638371  0.134022  0.875965  0.699404  654.0
1  0.901914  0.726308  0.519687  0.284857  0.183391    NaN

In [35]:
newdf = newdf.drop(0, axis=1)

In [36]:
newdf.head(2)

          A         B         C         D         E
0      6545  0.638371  0.134022  0.875965  0.699404
1  0.901914  0.726308  0.519687  0.284857  0.183391

In [37]:
newdf = pd.DataFrame(np.random.rand(334, 5), index=np.arange(334))

In [38]:
newdf

            0         1         2         3         4
0    0.588541  0.396503  0.626432  0.231782  0.006135
1    0.642003  0.112184  0.692233  0.140902  0.941857
2    0.089726  0.711651  0.625468  0.400924  0.153764
3    0.987020  0.726057  0.694519  0.319171  0.214241
4    0.328517  0.363458  0.585367  0.316339  0.086716
..        ...       ...       ...       ...       ...
329  0.911832  0.202661  0.583174  0.210052  0.777689
330  0.563133  0.305048  0.409086  0.539970  0.699664
331  0.980207  0.252129  0.694960  0.158341  0.880871
332  0.509940  0.372965  0.997562  0.175735  0.430297
333  0.978729  0.636325  0.092522  0.487138  0.248988

[334 rows x 5 columns]

In [39]:
newdf.head(2)

          0         1         2         3         4
0  0.588541  0.396503  0.626432  0.231782  0.006135
1  0.642003  0.112184  0.692233  0.140902  0.941857

In [40]:
newdf.loc[(newdf[1]<0.3) & (newdf[5]>0.1)]

KeyError: 5

In [ ]:
newdf.iloc[0, 4]

In [41]:
df = pd.DataFrame({
    'brand': ['Yum Yum', 'Yum Yum', 'Indomie', 'Indomie', 'Indomie'],
    'style': ['cup', 'cup', 'cup', 'pack', 'pack'],
    'rating': [4, 4, 3.5, 15, 5]
})

In [42]:
df.head()

     brand style  rating
0  Yum Yum   cup     4.0
1  Yum Yum   cup     4.0
2  Indomie   cup     3.5
3  Indomie  pack    15.0
4  Indomie  pack     5.0